[functions]
  [functions.environment]
  NETLIFY_AUTH_TOKEN = "your-netlify-auth-token"
  GIT_USER = "your-git-username"
  GIT_PASS = "your-git-password-or-pat"
[build]
  command = "npm run build"
  publish = ".next"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[plugins]]
  package = "@netlify/plugin-nextjs"
