name: Deploy Config

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if commit message contains '::auto-deploy::'
        id: check_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MESSAGE"

          # Check if the commit message contains '::auto-deploy::'
          if ! echo "$COMMIT_MESSAGE" | grep -q "::auto-deploy::"; then
            echo "Commit message does not contain '::auto-deploy::', skipping deployment.";
            exit 0
          fi

          # Extract orgName from commit message using regex
          if [[ "$COMMIT_MESSAGE" =~ "::auto-deploy::[[:space:]]*>[[:space:]]*(.*) ]]; then
            orgName="${BASH_REMATCH[1]}"
            echo "Extracted orgName: $orgName"
            echo "orgName=$orgName" >> $GITHUB_ENV  # Set the extracted orgName as an environment variable
          else
            echo "orgName not found in commit message, skipping deployment."
            exit 0
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Authenticate with Netlify
        run: netlify login --auth ${NETLIFY_AUTH_TOKEN}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Create site on Netlify using API
        id: create_site
        run: |
          RESPONSE=$(curl -X POST https://api.netlify.com/api/v1/sites \
            -H "Authorization: Bearer ${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
                "name": "ie-ook-za",
                "custom_domain": "ook.xhap.co.za",
                "team": "Humphrey Odilo'\''s team",
                "account_id": "60064e41e91328d07182bf09",
                "account_slug": "clinicplusdev",
                "account_name": "Humphrey Odilo'\''s team",
                "deploy_id": "678338abf2c6b90008d73118",
                "deploy_hook": "https://api.netlify.com/hooks/github",
                "user_id": "60064e41e91328d07182bf08",
                "admin_url": "https://app.netlify.com/sites/inaethe",
                "plan": "nf_team_pro",
                "premium": false,
                "claimed": true,
                "build_settings": {
                    "cmd": "npm run build",
                    "dir": ".next",
                    "installation_id": 44315287,
                    "untrusted_flow": "review",
                    "repo_type": "git",
                    "repo_branch": "main",
                    "repo_path": "namootatech/inaethe",
                    "repo_url": "https://github.com/namootatech/inaethe",
                    "repo_owner_type": "Organization",
                    "provider": "github",
                    "allowed_branches": ["main"],
                    "functions_dir": null,
                    "skip_prs": null,
                    "base_rel_dir": true,
                    "stop_builds": false,
                    "public_repo": false,
                    "skip_automatic_builds": null,
                    "configuration_file_path": null,
                    "package_path": ""
                }
                }')
          echo "Site creation response: $RESPONSE"

          # Extract site ID and name from the response
          SITE_ID=$(echo $RESPONSE | jq -r '.site_id')
          SITE_NAME=$(echo $RESPONSE | jq -r '.name')

          echo "NETLIFY_SITE_ID=$SITE_ID" >> $GITHUB_ENV
          echo "SITE_NAME=$SITE_NAME" >> $GITHUB_ENV

      - name: Set environment variables on Netlify
        run: |
          curl -X POST https://api.netlify.com/api/v1/sites/${{ env.NETLIFY_SITE_ID }}/env \
            -H "Authorization: Bearer ${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "NEXT_PUBLIC_API_URL": "${{ secrets.NEXT_PUBLIC_API_URL }}",
              "NEXT_PUBLIC_PAYFAST_URL" :"${{ secrets.NEXT_PUBLIC_PAYFAST_URL }}",
              "NEXT_PUBLIC_WEBSITE_URL" :"${{ secrets.NEXT_PUBLIC_WEBSITE_URL }}",
              "NEXT_PUBLIC_MERCHANT_ID" :"${{ secrets.NEXT_PUBLIC_MERCHANT_ID }}",
              "NEXT_PUBLIC_MERCHANT_KEY": "${{ secrets.NEXT_PUBLIC_MERCHANT_KEY }}",
              "NEXT_PUBLIC_GOOGLE_ANALYTICS": "${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }}",
              "NEXT_PUBLIC_MONGODB_URI": "${{ secrets.NEXT_PUBLIC_MONGODB_URI }}",
              "NEXT_PUBLIC_MONGODB_DB": "${{ secrets.NEXT_PUBLIC_MONGODB_DB }}",
              "NEXT_PUBLIC_CONFIG_NAME": "${orgName}.json",
              "NETLIFY_AUTH_TOKEN": "${{ secrets.NETLIFY_AUTH_TOKEN }}",
              "GIT_USER": "${{ secrets.GIT_USER }}",
              "GIT_PASS": "${{ secrets.GIT_PASS }}"
            }'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          SITE_NAME: ${{ env.SITE_NAME }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}

      - name: Link GitHub repo to Netlify
        run: netlify link --id ${{ env.NETLIFY_SITE_ID }} --name ${{ env.SITE_NAME }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          SITE_NAME: ${{ env.SITE_NAME }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}

      - name: Trigger deploy on Netlify
        run: netlify deploy --prod --trigger
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
