name: Deploy Config

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if commit message contains '::auto-deploy::'
        id: check_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MESSAGE"

          if ! echo "$COMMIT_MESSAGE" | grep -q "::auto-deploy::"; then
            echo "Commit message does not contain '::auto-deploy::', skipping deployment."
            exit 0
          fi

          if [[ "$COMMIT_MESSAGE" =~ "::auto-deploy::[[:space:]]*>[[:space:]]*(.*)" ]]; then
            orgName="${BASH_REMATCH[1]}"
            echo "orgName=$orgName" >> $GITHUB_ENV
          else
            echo "orgName not found in commit message, skipping deployment."
            exit 0
          fi

      - name: Fetch GitHub repo details
        id: fetch_github_details
        run: |
          REPO_DETAILS=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GIT_PASS }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}")
          echo "Repo details: $REPO_DETAILS"

          REPO_ID=$(echo "$REPO_DETAILS" | jq -r '.id')
          echo "repo_id=$REPO_ID" >> $GITHUB_ENV

          INSTALLATION_ID=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GIT_PASS }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/${{ github.repository }}/installation" | jq -r '.id')
          echo "installation_id=$INSTALLATION_ID" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Authenticate with Netlify
        run: netlify login --auth ${NETLIFY_AUTH_TOKEN}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Create site on Netlify using API
        id: create_site
        run: |
          PAYLOAD=$(cat <<EOF
          {
            "account_slug": "clinicplusdev",
            "name": "ie-${orgName}-za",
            "env": [
              {
                "key": "NEXT_PUBLIC_CONFIG_NAME",
                "scopes": ["builds", "functions", "runtime", "post_processing"],
                "values": [{"context": "all", "value": "${orgName}.json"}]
              },
              {
                "key": "NEXT_PUBLIC_API_URL",
                "scopes": ["builds", "functions", "runtime", "post_processing"],
                "values": [{"context": "all", "value": "${{ secrets.NEXT_PUBLIC_API_URL }}"}]
              },
              {
                "key": "NEXT_PUBLIC_PAYFAST_URL",
                "scopes": ["builds", "functions", "runtime", "post_processing"],
                "values": [{"context": "all", "value": "${{ secrets.NEXT_PUBLIC_PAYFAST_URL }}"}]
              },
              {
                "key": "NEXT_PUBLIC_WEBSITE_URL",
                "scopes": ["builds", "functions", "runtime", "post_processing"],
                "values": [{"context": "all", "value": "${{ secrets.NEXT_PUBLIC_WEBSITE_URL }}"}]
              },
              {
                "key": "NEXT_PUBLIC_MERCHANT_ID",
                "scopes": ["builds", "functions", "runtime", "post_processing"],
                "values": [{"context": "all", "value": "${{ secrets.NEXT_PUBLIC_MERCHANT_ID }}"}]
              },
              {
                "key": "NEXT_PUBLIC_MERCHANT_KEY",
                "scopes": ["builds", "functions", "runtime", "post_processing"],
                "values": [{"context": "all", "value": "${{ secrets.NEXT_PUBLIC_MERCHANT_KEY }}"}]
              },
              {
                "key": "NEXT_PUBLIC_GOOGLE_ANALYTICS",
                "scopes": ["builds", "functions", "runtime", "post_processing"],
                "values": [{"context": "all", "value": "${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }}"}]
              },
              {
                "key": "NEXT_PUBLIC_MONGODB_URI",
                "scopes": ["builds", "functions", "runtime", "post_processing"],
                "values": [{"context": "all", "value": "${{ secrets.NEXT_PUBLIC_MONGODB_URI }}"}]
              },
              {
                "key": "NEXT_PUBLIC_MONGODB_DB",
                "scopes": ["builds", "functions", "runtime", "post_processing"],
                "values": [{"context": "all", "value": "${{ secrets.NEXT_PUBLIC_MONGODB_DB }}"}]
              },
              {
                "key": "NETLIFY_AUTH_TOKEN",
                "scopes": ["builds", "functions", "runtime", "post_processing"],
                "values": [{"context": "all", "value": "${{ secrets.NETLIFY_AUTH_TOKEN }}"]
              },
              {
                "key": "GIT_USER",
                "scopes": ["builds", "functions", "runtime", "post_processing"],
                "values": [{"context": "all", "value": "${{ secrets.GIT_USER }}"}]
              },
              {
                "key": "GIT_PASS",
                "scopes": ["builds", "functions", "runtime", "post_processing"],
                "values": [{"context": "all", "value":"${{ secrets.GIT_PASS }}"}]
              }
            ],
            "account_slug":"clinicplusdev",
             "created_via": "",
             "default_hooks_data: {},
            "repo": {
              "provider": "github",
              "installation_id": ${{ env.installation_id }},
              "id": ${{ env.repo_id }},
              "repo": "namoota/inaethe",
              "owner_type": "Organization",
              "private": true,
              "branch": "main",
              "framework": "next",
              "frameworkName": "Next.js",
              "dir": ".next",
              "visualEditor": {
                "hasConfig": false
              },
              "frameworkLogo": {
               "default": "https://framework-info.netlify.app/logos/nextjs/light.svg",
               "light": "https://framework-info.netlify.app/logos/nextjs/light.svg",
               "dark": "https://framework-info.netlify.app/logos/nextjs/dark.svg"
              },
              "base": "",
              "siteName": "ie-${orgName}-za",
              "cmd": "npm run build",
              "plugins_installed": [],
              "plugins": [{"package": "@netlify/plugin-nextjs"}],
              "plugins_recommended": [
                  "@netlify/plugin-nextjs"
              ],
              "package_path": "",
              "framework": "next"
            }
          }
          EOF
          )

          echo "Site creation payload: $PAYLOAD"

          RESPONSE=$(curl -X POST https://api.netlify.com/api/v1/clinicplusdev/sites \
            -H "Authorization: Bearer ${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD")
          echo "Site creation response: $RESPONSE"

          SITE_ID=$(echo $RESPONSE | jq -r '.id')
          echo "NETLIFY_SITE_ID=$SITE_ID" >> $GITHUB_ENV
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          INSTALLATION_ID: ${{env.installation_id}}
          REPO_ID: ${{ env.repo_id }}

      - name: Trigger deploy on Netlify
        run: netlify deploy --prod --trigger
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
