# org-notifications/.github/workflows/notify.yml
name: Notify on Events

on:
  workflow_call:
    inputs:
      event:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Send Notification
        run: node sendNotification.js ${{ inputs.event }}
